name: 'Checkout'
description: 'Checkout a Git repository at a particular version'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
  actor:
    description: 'The current actor fetching the repository'
    default: ${{ github.actor }}
  token:
    description: 'The current token used for fetching the repository'
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
